import { httpResource } from '@angular/common/http';
import { computed, Injectable } from '@angular/core';
import { Book, BookYear } from './book';

/** Year desc, then `order` asc (unordered books last), then finished desc. Mirrors scripts/books.mjs. */
function compareBooks(a: Book, b: Book) {
  const byYear = b.finished.slice(0, 4).localeCompare(a.finished.slice(0, 4));
  if (byYear) return byYear;
  const byOrder = (a.order ?? Infinity) - (b.order ?? Infinity);
  if (byOrder) return byOrder;
  return b.finished.localeCompare(a.finished);
}

/** Reads public/books.json (generated by scripts/build-posts.mjs). */
@Injectable({ providedIn: 'root' })
export class BookService {
  private readonly resource = httpResource<Book[]>(() => 'books.json', { defaultValue: [] });

  readonly books = computed(() => this.resource.value());
  readonly isLoading = this.resource.isLoading;
  readonly error = this.resource.error;

  /** Books grouped by year finished: years newest first, then `order` within a year. */
  readonly byYear = computed<BookYear[]>(() => {
    const groups = new Map<string, Book[]>();
    for (const book of [...this.books()].sort(compareBooks)) {
      const year = book.finished.slice(0, 4);
      groups.set(year, [...(groups.get(year) ?? []), book]);
    }
    return [...groups].map(([year, books]) => ({ year, books }));
  });
}
