import { httpResource } from '@angular/common/http';
import { computed, Injectable } from '@angular/core';
import { Book, BookYear } from './book';

/** Reads public/books.json (generated by scripts/build-posts.mjs). */
@Injectable({ providedIn: 'root' })
export class BookService {
  private readonly resource = httpResource<Book[]>(() => 'books.json', { defaultValue: [] });

  readonly books = computed(() => this.resource.value());
  readonly isLoading = this.resource.isLoading;
  readonly error = this.resource.error;

  /** Books grouped by year finished. Sorting newest first also orders the years newest first. */
  readonly byYear = computed<BookYear[]>(() => {
    const groups = new Map<string, Book[]>();
    const newestFirst = [...this.books()].sort((a, b) => b.finished.localeCompare(a.finished));
    for (const book of newestFirst) {
      const year = book.finished.slice(0, 4);
      groups.set(year, [...(groups.get(year) ?? []), book]);
    }
    return [...groups].map(([year, books]) => ({ year, books }));
  });
}
