import { httpResource } from '@angular/common/http';
import { computed, Injectable } from '@angular/core';
import { Post } from './post';

/** Reads public/posts.json (generated by scripts/build-posts.mjs). Already sorted newest first. */
@Injectable({ providedIn: 'root' })
export class PostService {
  private readonly resource = httpResource<Post[]>(() => 'posts.json', { defaultValue: [] });

  readonly posts = computed(() => this.resource.value());
  readonly isLoading = this.resource.isLoading;
  readonly error = this.resource.error;

  latest(count: number) {
    return computed(() => this.posts().slice(0, count));
  }

  bySlug(slug: () => string) {
    return computed(() => this.posts().find((post) => post.slug === slug()));
  }
}
